//This file was generated by script mkregs.py

//address width
`define iob_timer_swreg_ADDR_W 2

//address macros
//Write addresses
`define TIMER_RESET_ADDR 0
`define TIMER_ENABLE_ADDR 1
`define TIMER_SAMPLE_ADDR 2
//Read Addresses
`define TIMER_DATA_HIGH_ADDR 0
`define TIMER_DATA_LOW_ADDR 4

//register/mem data width
`define TIMER_RESET_W 8
`define TIMER_ENABLE_W 8
`define TIMER_SAMPLE_W 8
`define TIMER_DATA_HIGH_W 32
`define TIMER_DATA_LOW_W 32

//mem address width
