// file generated by gen_defines.py
`define RUN_EXTMEM
`define USE_DDR
`define INIT_MEM
`define DATA_W 32
`define ADDR_W 32
`define BOOTROM_ADDR_W 12
`define SRAM_ADDR_W 12
`define FIRM_ADDR_W 17
`define DCACHE_ADDR_W 24
`define N_SLAVES 4
`define E 31
`define P 30
`define B 29
`define UART 0
`define TIMER 1
`define VERSAT 2
`define ETHERNET 3
`define N_SLAVES_W 2
`define USE_MUL_DIV 1
`define USE_COMPRESSED 1
`define DDR_DATA_W 32
`define DDR_ADDR_W 30
`define AXI_ADDR_W 32
